spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.255.179:3306/growup?serverTimezone=GMT%2B8&useSSL=true
    username: root   #数据库
    password: 1234 #密码
  mail:
    username: shy2210278285@aliyun.com
    password: zph770413
    host: smtp.aliyun.com


